### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2812

### ISSUE THREAD

**Issue by liuweizzuie** [zalando/expan#143]
here is an error of Unicode Issue:

```
C:\Users\ms>pip install expan
Collecting expan
  Downloading expan-0.6.0.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 146kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ms\AppData\Local\Temp\pip-build-v8f3gpor\expan\setup.py", line 15, in <module>
        readme = readme_file.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2812: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ms\AppData\Local\Temp\pip-build-v8f3gpor\expan\
```

python environment:
```
>python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by shansfolder** [comment]
Hi @liuweizzuie, I did a quick search, this seems to happen with Windows with default Chinese encoding with Python3. See a same discussion here: https://github.com/sshwsfc/xadmin/issues/330.

If you have some time, it would be great that you can open a Pull Request to branch ```dev``` that fixes it. Otherwise, we will plan it maybe in later days.

**Comment by CHI-MING-LEE** [comment]
Hi,
I found a solution that worked for me:
1. Download the .tar.gz file from PyPI
2. Download 7z unzip tools
3. Open tar.gz file with 7z tool and edit the line `open("ReadMe.rst")` before `readme = readme_file.read()`  as `open("ReadMe.rst", encoding="UTF-8")`
4. Save the change
5. Go into dos and execute `pip install xxx.tar.gz` <- the file you just modified

Hopefully you get your problem solved!
Ross

**Comment by shansfolder** [comment]
@CHI-MING-LEE thank you!
